### ISSUE TITLE
function validate_path() should tell me the invalid path

### ISSUE THREAD

**Issue by mobb** [EDIorg/EDIutils#15]
EAL uses this function. But R is not very good at tracing the problem for you, so scripts have to do it. Here is the message I get if EAL (EDI utils) cannot find a path: 
```
Error in EDIutils::validate_path(fun.args$path) : 
  The directory specified by the argument "path" does not exist! Please enter the correct path for your dataset working directory.
```

My script has several paths in it. the validate_path() should PRINT OUT the offending path to make it easier to track down.

**Comment by clnsmth** [comment]
This function is deprecated
