### ISSUE TITLE
include EDIutils in EDIorg-repository-index 

### ISSUE THREAD

**Issue by srearl** [EDIorg/EDIutils#16]
Please ignore if by design but otherwise note that `EDIutils` is not listed in the [EDIorg-repository-index](https://github.com/EDIorg/EDIorg-repository-index)

**Comment by clnsmth** [comment]
Thanks for the notification @srearl.

@mobb would you mind updating the index? I'm not sure how you'd like to list EDIutils.

**Comment by mobb** [comment]
related to 
https://github.com/EDIorg/EDIorg-repository-index/issues/1

**Comment by clnsmth** [comment]
Done
