### ISSUE TITLE
LTER affiliation no longer valid

### ISSUE THREAD

**Issue by srearl** [EDIorg/EDIutils#18]
Hi @clnsmth - I believe that since, @servilla changed the LDAP, that `LTER` as an option for the `affiliation` argument is no longer valid and should be removed. Below is a relevant snippet from `api_evaluate_data_package` but this may be relevant in other places within the package as well.
```
#' @param affiliation
#'     (character) Affiliation corresponding with the user.id argument supplied
#'     above. Can be: 'LTER' or 'EDI'.
```

**Comment by clnsmth** [comment]
Many thanks for reporting this issue @srearl. I have updated the authentication methods to redirect "LTER" affiliations to "EDI" behind the scenes so backwards compatibility is maintained (see version 1.3.0).
