### ISSUE TITLE
In vignettes/retrieve_downloads.Rmd  documentation on using .Renviron is confusing.

### ISSUE THREAD

**Issue by ARC-LTER** [EDIorg/EDIutils#31]
It is unclear what content to put in '.Renviron'  for login(). The Authentication section in invignettes/evaluate_and_upload.Rmd has a more extensive explanation of authenticating but not for using .Renviron.    From https://db.rstudio.com/best-practices/managing-credentials/  it looks like one could put  the following in the .Renviron file.
userId = "my_name"
userPass = "my_secert"
And use 
login(userId = Sys.getenv("userId"),userPass = Sys.getenv("userPass"))

**Comment by clnsmth** [comment]
Hi @ARC-LTER. The version of retrieve_downloads.Rmd you are referencing has been updated ([see here](https://github.com/EDIorg/EDIutils/blob/main/vignettes/retrieve_downloads.Rmd)). There's no need to add credentials to the .Renviron file.

**Comment by clnsmth** [comment]
The .Renviron file reference has been removed from the vignettes.
