### ISSUE TITLE
Error : 'validate_file_names' is not an exported object from 'namespace:EDIutils'

### ISSUE THREAD

**Issue by yvanlebras** [EDIorg/EDIutils#32]
Dear EDIutils team,

using a new test version of MetaShARK, we seen this error message when trying uploading a datafile to "infer" attribute names and related metadata:

`Error : 'validate_file_names' is not an exported object from 'namespace:EDIutils'`

Can you indicate us if there is an issue with the last version of the R package or maybe an error elsewhere ?

Wishing you a very good end of week !

Cheers,

Yvan

**Comment by clnsmth** [comment]
Thanks for the notification @yvanlebras. The error you're running into may be related to the recent EDIutils refactor ([see here for some context)](https://ediorg.github.io/EDIutils/news/index.html#ediutils-0009000). 

There's a good chance this error is arising from a previous release of EMLassemblyline that depended on the now deprecated version of EDIutils. The newest EMLassemblyline doesn't have this dependency and should work with MetaShARK. Try reinstalling EMLassemblyline `remotes::install_github("EMLassemblyline")` and/or the deprecated EDIutils (`remotes::install_github("EDIutils", ref = "deprecated"`).

I've relayed this information to @earnaud and it sounds a fix on the MetaShARK side is underway.

Please let me know if the issue persists, and my apologies for the inconvenience.

**Comment by earnaud** [comment]
Hi ! 
covidded @earnaud is back. I am checking this issue back: in definitive, if `EDIutils` dependency removed from `EMLassemblyline`, it shall be ok. Testing right now and ... I still get the error. To be sure: I shall use the current `development` branch of EAL?

**Comment by clnsmth** [comment]
Welcome back @earnaud!  

I just verified EMLassemblyline (all branches) and MetaShARK (master) do not use EDIutils or the function `validate_file_names()`, so I'm not sure why this is occurring. Only recommendation I have is to double check the EAL installation and verify EDIutils is not being called from MetaShARK.

**Comment by earnaud** [comment]
I had MetaShARK built with a dockerfile relying on a newer version of EAL and the issue was gone. Let's just keep it open a few days more if you will, so that @yvanlebras and I can assess it was due to an older version of EAL used in MetaShARK. 
I appreciate your efficiency for this issue.

**Comment by clnsmth** [comment]
@earnaud Has this issue been resolved?

**Comment by earnaud** [comment]
I believe it is, indeed.
