### ISSUE TITLE
detect_delimeter.R does not properly detect delimeters

### ISSUE THREAD

**Issue by earnaud** [EDIorg/EDIutils#6]
I am testing the EML Assembly Line which relies on the `detect_delimeter.R` script with .csv files. This CSV file is delimited by ";" (which is a norm using `read.csv2()` and `write.csv2()` ). 
## Edit
The error message itself is :
```r
I'm having trouble identifying the field delimeter of SupplementaryTable4.csv. Enter the field delimeter of this file. Valid options are:  ,  \t  ;  |
```
Thus indicating that .csv files can have separators in ,  \t  ;  |

**Comment by earnaud** [comment]
A solution could be to use the `try()` function with different separators instead of a `if()` (l. 141).

**Comment by earnaud** [comment]
New idea: 
```r
detect_delimeter_earnaud <- function(data.file){
    require(data.table)
    delims = c(",","\t",";","|")
    # build a vector of logical answering the question:
    # 'For each of my delimiters, is it possible to read @data.file without error?'
    tries <- sapply(delims, # for each of my delimiters
                    function(delim) 
                        class(try( # is it possible
                            fread(input = data.file,sep = delim) # to read @data.file
                        ))!= "try-error" # without error ? (e.g. shall return)
                    )
    
    if (is.null(delim.guess) || !any(tries)){ # not one of the tested values has been correct
        message(
            paste("I'm having trouble identifying the field delimeter of ", 
                  data.file, ". Enter the field delimeter of this file.",
                  ' Valid options are:  ,  \\t  ;  |', sep = ""))
        answer <- readline('ENTER here: ')
        if (answer == "\\t"){
            answer <- "\t"
        }
    } else {
        answer <- delim(tries)
    }
    return(answer)
}
```

**Comment by clnsmth** [comment]
Thanks for this idea @earnaud. I'm curious, which field delimiter can't be detected by the current version of `detect_delimeter()`?

**Comment by earnaud** [comment]
Well, I am using ";" delimited CSV files but `template_*()` functions send me the error message from `detect_delimiter()`. The above chunk of code shall detect the separator of data.file.  
Nota: I have not yet tested it.

**Comment by clnsmth** [comment]
I may have solved this issue @earnaud. Please reinstall `EDIutils` and let me know if the issue persists. Thanks!

**Comment by earnaud** [comment]
After reinstalling and re-running my script, the issue doesnot reappear. Problem solved ! Thank you.
